// src/utils/iconsConfig.js
import {
  // 📦 Padrão / Sistema
  Home,
  FileText,
  DollarSign,
  Users,
  Calendar,
  CheckCircle,
  AlertCircle,
  Star,
  Heart,
  Inbox,
  Archive,
  Trash2,
  Settings,
  Briefcase,
  ShoppingCart,
  Folder,
  FolderOpen,
  Tag,
  Lock,
  Unlock,
  Upload,
  Download,
  RefreshCw,
  Save,
  Power,
  LogOut,
  Filter,
  Search,
  Eye,
  EyeOff,

  // 🎓 Educação / Aprendizado
  Book,
  Notebook,
  GraduationCap,
  PenTool,
  Edit,
  Highlighter,
  ClipboardList,
  FileSignature,

  // 💼 Trabalho / Produtividade
  Target,
  BarChart3,
  PieChart,
  ChartLine,
  CalendarDays,
  ClipboardCheck,
  FileSpreadsheet,
  AlarmClock,
  Timer,
  Presentation,

  // 💬 Comunicação / Social
  Mail,
  Phone,
  MessageCircle,
  MessageSquare,
  AtSign,
  Mic,
  Video,
  Share2,
  User,
  UserPlus,
  UserMinus,
  Users2,

  // 💻 Tecnologia / TI
  Server,
  Database,
  Code,
  Cpu,
  GitBranch,
  GitCommit,
  GitPullRequest,
  Laptop,
  HardDrive,
  Network,
  Terminal,
  Bug,
  KeySquare,

  // 🎨 Design / Criatividade
  Palette,
  Lightbulb,
  Layers,
  Camera,
  Image,
  Brush,
  Scissors,
  Sparkles,
  Crop,
  Ruler,
  PenSquare,

  // ⚙️ Interface / Navegação
  Menu,
  Bell,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  Plus,
  Minus,
  Globe,
  MapPin,
  Compass,
  Info,
  HelpCircle,

  // 🌦️ Natureza / Clima
  Sun,
  Moon,
  Cloud,
  CloudRain,
  CloudSnow,
  Wind,
  Droplets,
  Leaf,
  TreePine,
  Flame
} from 'lucide-react';

// 🏷️ Nome dos ícones
export const iconLabels = {
  // 📦 Padrão / Sistema
  Home: 'Início',
  FileText: 'Arquivo',
  DollarSign: 'Dinheiro',
  Users: 'Usuários',
  Calendar: 'Calendário',
  CheckCircle: 'Concluído',
  AlertCircle: 'Alerta',
  Star: 'Favorito',
  Heart: 'Coração',
  Inbox: 'Entrada',
  Archive: 'Arquivo',
  Trash2: 'Lixeira',
  Settings: 'Configurações',
  Briefcase: 'Pasta',
  ShoppingCart: 'Carrinho',
  Folder: 'Pasta',
  FolderOpen: 'Pasta Aberta',
  Tag: 'Etiqueta',
  Lock: 'Bloqueado',
  Unlock: 'Desbloqueado',
  Upload: 'Enviar',
  Download: 'Baixar',
  RefreshCw: 'Atualizar',
  Save: 'Salvar',
  Power: 'Energia',
  LogOut: 'Sair',
  Filter: 'Filtro',
  Search: 'Buscar',
  Eye: 'Visualizar',
  EyeOff: 'Oculto',

  // 🎓 Educação / Aprendizado
  Book: 'Livro',
  Notebook: 'Caderno',
  GraduationCap: 'Faculdade',
  PenTool: 'Caneta',
  Edit: 'Editar',
  Highlighter: 'Marcador',
  ClipboardList: 'Lista',
  FileSignature: 'Assinatura',

  // 💼 Trabalho / Produtividade
  Target: 'Meta',
  BarChart3: 'Gráfico',
  PieChart: 'Pizza',
  ChartLine: 'Linha',
  CalendarDays: 'Dias',
  ClipboardCheck: 'Checklist',
  FileSpreadsheet: 'Planilha',
  AlarmClock: 'Alarme',
  Timer: 'Cronômetro',
  Presentation: 'Apresentação',

  // 💬 Comunicação / Social
  Mail: 'Email',
  Phone: 'Telefone',
  MessageCircle: 'Chat',
  MessageSquare: 'Mensagem',
  AtSign: 'Arroba',
  Mic: 'Microfone',
  Video: 'Vídeo',
  Share2: 'Compartilhar',
  User: 'Usuário',
  UserPlus: 'Adicionar Usuário',
  UserMinus: 'Remover Usuário',
  Users2: 'Grupo',

  // 💻 Tecnologia / TI
  Server: 'Servidor',
  Database: 'Banco de Dados',
  Code: 'Código',
  Cpu: 'Processador',
  GitBranch: 'Branch',
  GitCommit: 'Commit',
  GitPullRequest: 'Pull Request',
  Laptop: 'Notebook',
  HardDrive: 'Disco',
  Network: 'Rede',
  Terminal: 'Terminal',
  Bug: 'Bug',
  KeySquare: 'Chave',

  // 🎨 Design / Criatividade
  Palette: 'Paleta',
  Lightbulb: 'Ideia',
  Layers: 'Camadas',
  Camera: 'Câmera',
  Image: 'Imagem',
  Brush: 'Pincel',
  Scissors: 'Tesoura',
  Sparkles: 'Brilho',
  Crop: 'Cortar',
  Ruler: 'Régua',
  PenSquare: 'Caneta Quadrada',

  // ⚙️ Interface / Navegação
  Menu: 'Menu',
  Bell: 'Notificação',
  ChevronRight: 'Seta Direita',
  ChevronLeft: 'Seta Esquerda',
  ChevronDown: 'Seta Baixo',
  ChevronUp: 'Seta Cima',
  Plus: 'Adicionar',
  Minus: 'Remover',
  Globe: 'Mundo',
  MapPin: 'Localização',
  Compass: 'Bússola',
  Info: 'Informação',
  HelpCircle: 'Ajuda',

  // 🌦️ Natureza / Clima
  Sun: 'Sol',
  Moon: 'Lua',
  Cloud: 'Nuvem',
  CloudRain: 'Chuva',
  CloudSnow: 'Neve',
  Wind: 'Vento',
  Droplets: 'Gotas',
  Leaf: 'Folha',
  TreePine: 'Árvore',
  Flame: 'Fogo'
};

// 🔗 Mapa de ícones
export const iconMap = {
  // 📦 Padrão / Sistema
  Home,
  FileText,
  DollarSign,
  Users,
  Calendar,
  CheckCircle,
  AlertCircle,
  Star,
  Heart,
  Inbox,
  Archive,
  Trash2,
  Settings,
  Briefcase,
  ShoppingCart,
  Folder,
  FolderOpen,
  Tag,
  Lock,
  Unlock,
  Upload,
  Download,
  RefreshCw,
  Save,
  Power,
  LogOut,
  Filter,
  Search,
  Eye,
  EyeOff,

  // 🎓 Educação / Aprendizado
  Book,
  Notebook,
  GraduationCap,
  PenTool,
  Edit,
  Highlighter,
  ClipboardList,
  FileSignature,

  // 💼 Trabalho / Produtividade
  Target,
  BarChart3,
  PieChart,
  ChartLine,
  CalendarDays,
  ClipboardCheck,
  FileSpreadsheet,
  AlarmClock,
  Timer,
  Presentation,

  // 💬 Comunicação / Social
  Mail,
  Phone,
  MessageCircle,
  MessageSquare,
  AtSign,
  Mic,
  Video,
  Share2,
  User,
  UserPlus,
  UserMinus,
  Users2,

  // 💻 Tecnologia / TI
  Server,
  Database,
  Code,
  Cpu,
  GitBranch,
  GitCommit,
  GitPullRequest,
  Laptop,
  HardDrive,
  Network,
  Terminal,
  Bug,
  KeySquare,

  // 🎨 Design / Criatividade
  Palette,
  Lightbulb,
  Layers,
  Camera,
  Image,
  Brush,
  Scissors,
  Sparkles,
  Crop,
  Ruler,
  PenSquare,

  // ⚙️ Interface / Navegação
  Menu,
  Bell,
  ChevronRight,
  ChevronLeft,
  ChevronDown,
  ChevronUp,
  Plus,
  Minus,
  Globe,
  MapPin,
  Compass,
  Info,
  HelpCircle,

  // 🌦️ Natureza / Clima
  Sun,
  Moon,
  Cloud,
  CloudRain,
  CloudSnow,
  Wind,
  Droplets,
  Leaf,
  TreePine,
  Flame
};
